import express from 'express';
import cors from 'cors';

const app = express();

app.use(cors());
app.use(express.json());

// Simple test endpoint
app.post('/api/script-doctor/analyze', (req, res) => {
  console.log('Analysis request received:', req.body);
  
  const mockResponse = {
    suggestions: [
      {
        id: 'test-1',
        type: 'structure',
        title: 'Test Suggestion',
        description: 'This is a test suggestion from the simplified server.',
        severity: 'medium'
      }
    ],
    overallScore: 75,
    summary: 'Test analysis completed successfully.',
    success: true,
    timestamp: new Date().toISOString()
  };
  
  res.json(mockResponse);
});

// Generate script endpoint
app.post('/api/generate-script', (req, res) => {
  console.log('Script generation request:', req.body);
  
  res.json({
    success: true,
    script: `INT. TEST ROOM - DAY

A simple test script generated by the simplified server.

ALEX
This is working!

FADE OUT.`
  });
});

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

const PORT = 4000;
app.listen(PORT, () => {
  console.log(`Simplified API server running on port ${PORT}`);
});