name = "readyscriptpro"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "readyscriptpro"
route = "readyscriptpro.com/*"
zone_id = "your_zone_id_here"

[env.production.vars]
NODE_ENV = "production"
FRONTEND_URL = "https://readyscriptpro.com"

# 如果需要API功能，取消注释并填入你的API密钥
# CLAUDE_API_KEY = "your_claude_api_key_here"
# OPENROUTER_API_KEY = "your_openrouter_api_key_here"

[build]
command = "npm run build"
watch_dir = "src"

[build.upload]
format = "service-worker"

[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

[[redirects]]
from = "/generate"
to = "/studio"
status = 301

[[redirects]]
from = "/script-generator"
to = "/studio"
status = 301

[[redirects]]
from = "/create"
to = "/studio"
status = 301 