[build]
command = "npm run build"
[build.upload]
format = "directory"
dir = "dist"  # 或者你的构建输出目录

pages_build_output_dir = "dist"

[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

[[redirects]]
from = "/generate"
to = "/studio"
status = 301

[[redirects]]
from = "/script-generator"
to = "/studio"
status = 301

[[redirects]]
from = "/create"
to = "/studio"
status = 301 